- name: get python-nose
  become: true
  command: apt-get install -y python-nose

- name: run all guest tests
  become: true
  command: "{{ item }}"
  with_items:
    - pwd
    - ls -all
    - ./run_all_guest_tests.sh
  args:
     chdir: guest

- name: shutdown guest vm if test_and_shutdown is set
  become: true
  command: "{{ item }}"
  with_items:
    - "free && sync && sh -c 'echo 3 > /proc/sys/vm/drop_caches' && free"
    - 'shutdown -P now'
  when: test_and_shutdown
