# Verify status of KVM and VT
- include: kvm-vt.yml
# Verify gtest exists
- include: gtest.yml
# Verify bear exists
- include: bear.yml
# Verify libwebsockets exist
- include: libwebsockets.yml
# Verify qt3 exist
- include: qt3.yml
