- name: build qemu
  shell: >
      ./configure --enable-io-thread --enable-linux-aio --target-list=x86_64-softmmu --enable-sdl --enable-vssim --extra-cflags='-Wno-error=unused-but-set-variable -Wno-error=deprecated-declarations -Wno-error=cpp' --cc={{ gcc }} --enable-xen && make
  args:
    chdir: "{{ dest }}/eVSSIM/QEMU"
    creates: "{{ dest }}/eVSSIM/QEMU/x86_64-softmmu/qemu-system-x86_64"

# Newer version of SeaBIOS is required to allow booting directly with a Linux kernel image.
- name: overwrite bios.bin
  copy:
  args:
    src: bios.bin
    dest: "{{ dest }}/eVSSIM/QEMU/pc-bios/bios.bin"

- name: copy kernel
  copy:
  args:
    src: "{{kernel_image}}"
    dest: "{{ dest }}/{{kernel_image}}"

- name: copy initrd
  copy:
  args:
    src: "{{initrd_image}}"
    dest: "{{ dest }}/{{initrd_image}}"

- name: prepare fio_tests.tar
  shell: tar -cvf fio_tests.tar fio_tests
  args:
    chdir: "{{ dest }}/eVSSIM"
    creates: "{{ dest }}/eVSSIM/fio_tests.tar"
