---
- name: configure prerequisites
  hosts: [host_testers, guest_testers]
  roles:
    - common
  environment:
    http_proxy: "{{ lookup('env','http_proxy') }}"
    https_proxy: "{{ lookup('env','http_proxy') }}"
  tags: [host, guest, common]

- name: run elk stack
  hosts: host_testers
  roles:
    - elk_docker_setup
  tags: host

- name: perform host tests
  hosts: host_testers
  roles:
    - host_tester
  tags: host

- name: prepare image to run tests and leave instatce active
  hosts: guest_testers
  roles:
    - { role: guest_tester_pre, ssd_storage_strategy: 1, prepare_image: true, activate_instance: true }
  tags: guest

- name: perform guest tests with STORAGE_STRATEGY_SECTOR
  hosts: guests
  roles:
    - { role: guest_tester, ssd_storage_strategy: 1, test_and_shutdown: true }
  tags: guest

#- name:  stop
#  hosts: localhost
#  gather_facts: False
#  tasks:
#    - name: stop here
#      fail:
#        msg: "STORAGE_STRATEGY_OBJECT wasnt exercised"
# TODO  stop here if dev-option == run setup and tests for STORAGE_STRATEGY_SECTOR


- name: skip image preparation, only actiavte instance
  hosts: guest_testers
  roles:
    - { role: guest_tester_pre, ssd_storage_strategy: 2, prepare_image: false, activate_instance: true }
  tags: guest


- name: perform guest tests with OBJECT_STRATEGY_OBJECT
  hosts: guests
  roles:
    - { role: guest_tester, ssd_storage_strategy: 2, test_and_shutdown: false }
  tags: guest

